### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZefianAlfian** [krypton-byte/Twibbonizze.js#1]
![Screenshot_20211110-211250_Termux](https://user-images.githubusercontent.com/70304409/141128801-57c5b4e5-bb8c-48f7-844b-eb864ebdc8f1.jpg)

**Comment by krypton-byte** [comment]
(new Twibbonizze("twibbonkbi")).create("image.jpg").then(console.log)

**Comment by ZefianAlfian** [comment]
oooo gitu
